### ISSUE TITLE
aula 3 correção 

### ISSUE THREAD

**Issue by eudenesmn** [loiane/curso-java-basico#20]
professora , nesse exercicio quando coloco 2.5 o ja nao entede o meu poto aparce uma mensagem essa mensagem de erro o que eu faço? e o que significa esse erro?
grato desde ja pelo curso .

Exception in thread "main" java.util.InputMismatchException
	at java.base/java.util.Scanner.throwFor(Scanner.java:939)
	at java.base/java.util.Scanner.next(Scanner.java:1594)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2258)
	at java.base/java.util.Scanner.nextInt(Scanner.java:2212)
	at com.loiane.curso_java13.labs.Exer05.main(Exer05.java:10)

**Comment by gilmarhonorato** [comment]
Olá, comigo aconteceu a mesma coisa. E percebi que o padrão de número utilizado no EUA é 0.00 o contraário que utilizamos aqui no BR. Tente digitar o valor 2,5 que vai retornar pra voce sem erro.
![image](https://user-images.githubusercontent.com/68576796/170162340-ed23cf86-a5e8-41e2-a92e-8701efbc5d3d.png)
Abaixo digitei 2,5;
![image](https://user-images.githubusercontent.com/68576796/170162436-55a78e7e-f26a-4404-8bc6-691cf64e8bb4.png)
